version: '3.8'

services:
  db:
    container_name: dicom-viewer-db 
    image: postgres:latest
    environment:
      POSTGRES_USER: levi
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432" 
    networks:
      - db 
      - app 
    restart: unless-stopped

  backend:
    container_name: springboot-backend
    # build:
    #   context: ./backend/dicom-viewer-backend/
    #   dockerfile: Dockerfile
    image: maven:3.9.6-eclipse-temurin-21 

    command: ["mvn", "spring-boot:run"]
    ports:
      - "8080:8080"

    volumes:
    - ./backend/dicom-viewer-backend:/usr/src/app # Mount project root
    - ~/.m2:/root/.m2                             # Mount local Maven cache for speed

    working_dir: /usr/src/app

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: levi
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app
      - db
    depends_on:
      - db

  go-service:
    container_name: go-microservice
    build:
      context: ./services/
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./services:/app
    networks:
      - app
      - db
    depends_on:
      - db

  frontend:
    container_name: nextjs-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - backend 

    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm","run","dev"]

networks:
  db:
    driver: bridge
  app:
    driver: bridge

volumes:
  db:
